### ISSUE TITLE
yarn build报错

### ISSUE THREAD

**Issue by wutong233** [unicar9/jizhi#136]
[root@iZva01gaj2xsb8Z jizhi]# yarn build
yarn run v1.22.4
$ webpack --mode production && node build.js
/home/jizhi/webpack.config.js:13
    ...config,
    ^^^

SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (/home/jizhi/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/jizhi/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/home/jizhi/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/jizhi/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/home/jizhi/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /home/jizhi/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (native)
    at module.exports (/home/jizhi/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at yargs.parse.err (/home/jizhi/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/home/jizhi/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/jizhi/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/jizhi/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jizhi/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by unicar9** [comment]
@wutong233 没发现这个问题，但是 eslint 报错改了一下，现在 pull 最新代码试试呢？

**Comment by wutong233** [comment]
> @wutong233 没发现这个问题，但是 eslint 报错改了一下，现在 pull 最新代码试试呢？

仍然报错,从clone到结束的日志都在下面了
[root@iZva01gaj2xsb8Z jizhi]# git clone https://gitee.com/heliumw/jizhi.git
正克隆到 'jizhi'...
Username for 'https://gitee.com': heliumw
Password for 'https://heliumw@gitee.com': 
remote: Enumerating objects: 1141, done.
remote: Counting objects: 100% (1141/1141), done.
remote: Compressing objects: 100% (435/435), done.
remote: Total 1141 (delta 692), reused 1141 (delta 692), pack-reused 0
接收对象中: 100% (1141/1141), 11.20 MiB | 3.68 MiB/s, done.
处理 delta 中: 100% (692/692), done.
[root@iZva01gaj2xsb8Z jizhi]# ls
jizhi
[root@iZva01gaj2xsb8Z jizhi]# cd jizhi/
[root@iZva01gaj2xsb8Z jizhi]# ls
build.js              firefox.background.js  src
CHANGELOG.md          firefox.manifest.json  webpack.config.js
chrome.background.js  jest.config.js         yarn.lock
chrome.manifest.json  package.json
examples              README.md
[root@iZva01gaj2xsb8Z jizhi]# yarn
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > react-hot-loader@4.12.20" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
warning " > react-p5-wrapper@0.0.4" has incorrect peer dependency "react@^0.14.0".
warning "@neutrinojs/jest > eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > @neutrinojs/standardjs@9.1.0" has incorrect peer dependency "eslint@^6.0.0".
warning "@neutrinojs/standardjs > @neutrinojs/eslint@9.1.0" has incorrect peer dependency "eslint@^6.0.0".
warning "@neutrinojs/standardjs > eslint-config-standard@14.1.0" has incorrect peer dependency "eslint@>=6.2.2".
warning "@neutrinojs/standardjs > eslint-config-standard-react@9.2.0" has incorrect peer dependency "eslint@>=6.2.2".
warning "@neutrinojs/standardjs > eslint-config-standard-react > eslint-config-standard-jsx@8.1.0" has incorrect peer dependency "eslint@>=6.2.2".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 360.61s.
[root@iZva01gaj2xsb8Z jizhi]# ls
build.js              firefox.background.js  README.md
CHANGELOG.md          firefox.manifest.json  src
chrome.background.js  jest.config.js         webpack.config.js
chrome.manifest.json  node_modules           yarn.lock
examples              package.json
[root@iZva01gaj2xsb8Z jizhi]# yarn build
yarn run v1.22.4
$ webpack --mode production && node build.js
/www/wwwroot/jizhi/jizhi/webpack.config.js:13
    ...config,
    ^^^

SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (/www/wwwroot/jizhi/jizhi/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/www/wwwroot/jizhi/jizhi/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/www/wwwroot/jizhi/jizhi/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/www/wwwroot/jizhi/jizhi/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/www/wwwroot/jizhi/jizhi/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /www/wwwroot/jizhi/jizhi/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (native)
    at module.exports (/www/wwwroot/jizhi/jizhi/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at yargs.parse.err (/www/wwwroot/jizhi/jizhi/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/www/wwwroot/jizhi/jizhi/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /www/wwwroot/jizhi/jizhi/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/www/wwwroot/jizhi/jizhi/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/www/wwwroot/jizhi/jizhi/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by BrandNewLifeJackie26** [comment]
Hello请问这个问题解决了吗？我build也出了些问题，是不是有些依赖有问题？
```
$ yarn build
yarn run v1.22.5
$ webpack --mode production && node build.js
Hash: d9383e66740f413bc7e2d9383e66740f413bc7e2
Version: webpack 4.42.1
Child
    Hash: d9383e66740f413bc7e2
    Time: 1549ms
    Built at: 2020-09-01 4:10:58 ├F10: PM┤
     2 assets

    ERROR in ./src/index.jsx
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
    Require stack:
    - F:\Repos\jizhi\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js
    - F:\Repos\jizhi\node_modules\@babel\preset-env\lib\index.js
    - F:\Repos\jizhi\node_modules\@babel\core\lib\config\files\plugins.js
    - F:\Repos\jizhi\node_modules\@babel\core\lib\config\files\index.js
    - F:\Repos\jizhi\node_modules\@babel\core\lib\index.js
    - F:\Repos\jizhi\node_modules\babel-merge\src\index.js
    - F:\Repos\jizhi\node_modules\@neutrinojs\web\index.js
    - F:\Repos\jizhi\node_modules\@neutrinojs\react\index.js
    - F:\Repos\jizhi\.neutrinorc.js
    - F:\Repos\jizhi\node_modules\neutrino\index.js
    - F:\Repos\jizhi\webpack.config.js
    - F:\Repos\jizhi\node_modules\webpack-cli\bin\utils\convert-argv.js
    - F:\Repos\jizhi\node_modules\webpack-cli\bin\cli.js
    - F:\Repos\jizhi\node_modules\webpack\bin\webpack.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
        at Function.Module._load (internal/modules/cjs/loader.js:841:27)
        at Module.require (internal/modules/cjs/loader.js:1025:19)
        at require (F:\Repos\jizhi\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
        at Object.<anonymous> (F:\Repos\jizhi\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js:10:55)
        at Module._compile (F:\Repos\jizhi\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
        at Module.load (internal/modules/cjs/loader.js:985:32)
        at Function.Module._load (internal/modules/cjs/loader.js:878:14)
        at Module.require (internal/modules/cjs/loader.js:1025:19)
        at require (F:\Repos\jizhi\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
        at Object.<anonymous> (F:\Repos\jizhi\node_modules\@babel\preset-env\lib\index.js:29:44)
        at Module._compile (F:\Repos\jizhi\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
        at Module.load (internal/modules/cjs/loader.js:985:32)
        at Function.Module._load (internal/modules/cjs/loader.js:878:14)
        at Module.require (internal/modules/cjs/loader.js:1025:19)
        at require (F:\Repos\jizhi\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
        at requireModule (F:\Repos\jizhi\node_modules\@babel\core\lib\config\files\plugins.js:165:12)
        at loadPreset (F:\Repos\jizhi\node_modules\@babel\core\lib\config\files\plugins.js:83:17)
        at createDescriptor (F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
        at F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-descriptors.js:109:50
        at Array.map (<anonymous>)
        at createDescriptors (F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
        at createPresetDescriptors (F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
        at F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-descriptors.js:58:104
        at cachedFunction (F:\Repos\jizhi\node_modules\@babel\core\lib\config\caching.js:62:27)
        at cachedFunction.next (<anonymous>)
        at evaluateSync (F:\Repos\jizhi\node_modules\gensync\index.js:244:28)
        at sync (F:\Repos\jizhi\node_modules\gensync\index.js:84:14)
        at presets (F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-descriptors.js:29:84)
        at mergeChainOpts (F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-chain.js:320:26)
        at F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-chain.js:283:7
        at Generator.next (<anonymous>)
        at buildRootChain (F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-chain.js:68:36)
        at buildRootChain.next (<anonymous>)
     @ multi ./src/index index[0]
Child
    Hash: d9383e66740f413bc7e2
    Time: 1521ms
    Built at: 2020-09-01 4:10:58 ├F10: PM┤
     2 assets

    ERROR in ./src/index.jsx
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
    Require stack:
    - F:\Repos\jizhi\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js
    - F:\Repos\jizhi\node_modules\@babel\preset-env\lib\index.js
    - F:\Repos\jizhi\node_modules\@babel\core\lib\config\files\plugins.js
    - F:\Repos\jizhi\node_modules\@babel\core\lib\config\files\index.js
    - F:\Repos\jizhi\node_modules\@babel\core\lib\index.js
    - F:\Repos\jizhi\node_modules\babel-merge\src\index.js
    - F:\Repos\jizhi\node_modules\@neutrinojs\web\index.js
    - F:\Repos\jizhi\node_modules\@neutrinojs\react\index.js
    - F:\Repos\jizhi\.neutrinorc.js
    - F:\Repos\jizhi\node_modules\neutrino\index.js
    - F:\Repos\jizhi\webpack.config.js
    - F:\Repos\jizhi\node_modules\webpack-cli\bin\utils\convert-argv.js
    - F:\Repos\jizhi\node_modules\webpack-cli\bin\cli.js
    - F:\Repos\jizhi\node_modules\webpack\bin\webpack.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
        at Function.Module._load (internal/modules/cjs/loader.js:841:27)
        at Module.require (internal/modules/cjs/loader.js:1025:19)
        at require (F:\Repos\jizhi\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
        at Object.<anonymous> (F:\Repos\jizhi\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js:10:55)
        at Module._compile (F:\Repos\jizhi\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
        at Module.load (internal/modules/cjs/loader.js:985:32)
        at Function.Module._load (internal/modules/cjs/loader.js:878:14)
        at Module.require (internal/modules/cjs/loader.js:1025:19)
        at require (F:\Repos\jizhi\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
        at Object.<anonymous> (F:\Repos\jizhi\node_modules\@babel\preset-env\lib\index.js:29:44)
        at Module._compile (F:\Repos\jizhi\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
        at Module.load (internal/modules/cjs/loader.js:985:32)
        at Function.Module._load (internal/modules/cjs/loader.js:878:14)
        at Module.require (internal/modules/cjs/loader.js:1025:19)
        at require (F:\Repos\jizhi\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
        at requireModule (F:\Repos\jizhi\node_modules\@babel\core\lib\config\files\plugins.js:165:12)
        at loadPreset (F:\Repos\jizhi\node_modules\@babel\core\lib\config\files\plugins.js:83:17)
        at createDescriptor (F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
        at F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-descriptors.js:109:50
        at Array.map (<anonymous>)
        at createDescriptors (F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
        at createPresetDescriptors (F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
        at F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-descriptors.js:58:104
        at cachedFunction (F:\Repos\jizhi\node_modules\@babel\core\lib\config\caching.js:62:27)
        at cachedFunction.next (<anonymous>)
        at evaluateSync (F:\Repos\jizhi\node_modules\gensync\index.js:244:28)
        at sync (F:\Repos\jizhi\node_modules\gensync\index.js:84:14)
        at presets (F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-descriptors.js:29:84)
        at mergeChainOpts (F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-chain.js:320:26)
        at F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-chain.js:283:7
        at Generator.next (<anonymous>)
        at buildRootChain (F:\Repos\jizhi\node_modules\@babel\core\lib\config\config-chain.js:68:36)
        at buildRootChain.next (<anonymous>)
     @ multi ./src/index index[0]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wutong233** [comment]
yarn版本问题，安装最新版即可，不要直接用apt安装
